# Generated by Django 5.0.3 on 2024-04-03 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Ingrediente', models.TextField(max_length=2000)),
                ('Modo_de_Preparo', models.TextField(max_length=8000)),
                ('Grau_de_Dificuldade', models.CharField(blank=True, choices=[('Facil', 'Facil'), ('Moderado', 'Moderado'), ('Dificil', 'Dificil')], max_length=10, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceitaApp.categoria')),
            ],
        ),
    ]
