# Generated by Django 5.0.3 on 2024-04-03 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='Ingrediente',
            new_name='Ingredientes',
        ),
        migrations.AlterField(
            model_name='receita',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ReceitaApp.categoria'),
        ),
    ]
